In [1]:
import pandas as pd

In [2]:
import numpy as np


In [3]:
labels = ["a","b","c"]

In [4]:
mylist = [10, 20, 30]

In [14]:
array = np.array(mylist)
array

array([10, 20, 30])

In [12]:
dict = {'a':1,'b':2,'c':3}

In [13]:
dict

{'a': 1, 'b': 2, 'c': 3}

In [16]:
pd.Series(mylist)

0    10
1    20
2    30
dtype: int64

In [20]:
pd.Series(array, index =labels)

a    10
b    20
c    30
dtype: int32

In [27]:
series1 = pd.Series(data = [1,2,3,4], index = ["USA", "Germany", "USSR", "Japan"])

In [28]:
series1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [29]:
series1["USSR"]

3

In [30]:
series2 = pd.Series(data = [1,4,5,6], index = ["USA","Germany","Italy","Japan"])

In [31]:
series2

USA        1
Germany    4
Italy      5
Japan      6
dtype: int64

In [32]:
series1+series2

Germany     6.0
Italy       NaN
Japan      10.0
USA         2.0
USSR        NaN
dtype: float64

In [34]:
np.random.seed(101)
randmat = np.random.randn(5,4)
randmat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [39]:
df = pd.DataFrame(randmat, columns= "A B C D".split(), index = "a b c d e".split())

In [40]:
df

A         B         C         D
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [47]:
sum(df["A"])

1.7192891751267547

In [49]:
df["D B".split()]

D         B
a  0.503826  0.628133
b  0.605965 -0.319318
c -0.589001  0.740122
d  0.955057 -0.758872
e  0.683509  1.978757

In [50]:
df["E"] = df["A"]+df["D"]

In [57]:
df.drop("E", axis=1, inplace = True)

In [58]:
df

A         B         C         D
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [60]:
df.drop("a", inplace =True)

In [61]:
df

A         B         C         D
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [62]:
df.loc["b"]

A    0.651118
B   -0.319318
C   -0.848077
D    0.605965
Name: b, dtype: float64

In [63]:
df.iloc[0]

A    0.651118
B   -0.319318
C   -0.848077
D    0.605965
Name: b, dtype: float64

In [67]:
df.loc[["c", "d"]]

A         B         C         D
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057

In [68]:
df.iloc[[3,1]]

A         B         C         D
e  0.190794  1.978757  2.605967  0.683509
c -2.018168  0.740122  0.528813 -0.589001

In [69]:
df

A         B         C         D
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [70]:
df.loc[["c","d"],["C","D"]]

C         D
c  0.528813 -0.589001
d -0.933237  0.955057

In [71]:
df

A         B         C         D
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [72]:
df[df>0]

A         B         C         D
b  0.651118       NaN       NaN  0.605965
c       NaN  0.740122  0.528813       NaN
d  0.188695       NaN       NaN  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [75]:
df["A"]>0

b     True
c    False
d     True
e     True
Name: A, dtype: bool

In [76]:
df[df["A"]>0]

A         B         C         D
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [79]:
df[df["A"]>0]["C"].loc["d"]

-0.9332372163009188

In [81]:
cond1 = df["B"]>0
cond2 = df["C"]>1

In [82]:
df[cond1 & cond2]

A         B         C         D
e  0.190794  1.978757  2.605967  0.683509

In [84]:
df[(df["B"] >0) & (df["C"]>1)]

A         B         C         D
e  0.190794  1.978757  2.605967  0.683509

In [85]:
df

A         B         C         D
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [90]:
new_col = "ny ca mi or".split()

In [91]:
new_col

['ny', 'ca', 'mi', 'or']

In [92]:
df["states"]= new_col

In [93]:
df

A         B         C         D states
b  0.651118 -0.319318 -0.848077  0.605965     ny
c -2.018168  0.740122  0.528813 -0.589001     ca
d  0.188695 -0.758872 -0.933237  0.955057     mi
e  0.190794  1.978757  2.605967  0.683509     or

In [94]:
df.reset_index()

index         A         B         C         D states
0     b  0.651118 -0.319318 -0.848077  0.605965     ny
1     c -2.018168  0.740122  0.528813 -0.589001     ca
2     d  0.188695 -0.758872 -0.933237  0.955057     mi
3     e  0.190794  1.978757  2.605967  0.683509     or

In [96]:
df.set_index(keys="states")

A         B         C         D
states                                        
ny      0.651118 -0.319318 -0.848077  0.605965
ca     -2.018168  0.740122  0.528813 -0.589001
mi      0.188695 -0.758872 -0.933237  0.955057
or      0.190794  1.978757  2.605967  0.683509

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, b to e
Data columns (total 5 columns):
A         4 non-null float64
B         4 non-null float64
C         4 non-null float64
D         4 non-null float64
states    4 non-null object
dtypes: float64(4), object(1)
memory usage: 352.0+ bytes


In [99]:
df.dtypes

A         float64
B         float64
C         float64
D         float64
states     object
dtype: object

In [101]:
df.describe()

A         B         C         D
count  4.000000  4.000000  4.000000  4.000000
mean  -0.246890  0.410172  0.338367  0.413883
std    1.200715  1.220402  1.653573  0.685137
min   -2.018168 -0.758872 -0.933237 -0.589001
25%   -0.363021 -0.429207 -0.869367  0.307224
50%    0.189745  0.210402 -0.159632  0.644737
75%    0.305875  1.049781  1.048102  0.751396
max    0.651118  1.978757  2.605967  0.955057

In [103]:
df.shape

(4, 5)

In [104]:
df

A         B         C         D states
b  0.651118 -0.319318 -0.848077  0.605965     ny
c -2.018168  0.740122  0.528813 -0.589001     ca
d  0.188695 -0.758872 -0.933237  0.955057     mi
e  0.190794  1.978757  2.605967  0.683509     or

In [107]:
df.loc[["c"],["states"]]

states
c     ca

In [114]:
c = df["C"] > 0

In [115]:
c.value_counts()

True     2
False    2
Name: C, dtype: int64

In [122]:
c.count()

4

# working with nan values

In [123]:
df = pd.DataFrame({"A":[1,2,np.nan],"B":[5,np.nan,np.nan],"C":[1,2,3]})

In [118]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [121]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [132]:
df.dropna(axis=0,thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [133]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [143]:
df["B"].dropna()

0    5.0
Name: B, dtype: float64

In [134]:
df.fillna(value = "null", )

A     B  C
0     1     5  1
1     2  null  2
2  null  null  3

In [142]:
df["B"].fillna(value = 4)

0    5.0
1    4.0
2    4.0
Name: B, dtype: float64

In [144]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [145]:
df.fillna(df.mean())

A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

In [146]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [150]:
df["B"].fillna(value = df["B"].mean())

0    5.0
1    5.0
2    5.0
Name: B, dtype: float64

In [151]:
df["A"].fillna(value = df["A"].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

## performing group_by operations in python.

In [158]:
df1= pd.DataFrame({"category":['A','A','B','B','C','C'], "Data_Value":[10,5,2,4,12,6]})

In [159]:
df1

category  Data_Value
0        A          10
1        A           5
2        B           2
3        B           4
4        C          12
5        C           6

In [160]:
df2 = pd.DataFrame({"Company":["GOOG","GOOG","MSFT","MSFT","FB","FB"],"Person":["Charlie","Sam","Army","Vanessa","Carl","Sarah"],"Sales":[200,120,340,124,243,350]})

In [161]:
df2

Company   Person  Sales
0    GOOG  Charlie    200
1    GOOG      Sam    120
2    MSFT     Army    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [165]:
df2.groupby(df2["Company"]).mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [166]:
df2.groupby("Company").max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [167]:
df2.groupby("Company").min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT        Army    124

In [170]:
df2.groupby("Company").count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [171]:
df2.groupby("Company").std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [172]:
df2.groupby("Company").describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [174]:
df2.groupby("Company").describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

# operations

In [175]:
df3 = pd.DataFrame({"col1":[1,2,3,4], "col2":[444,555,666,444], "col3":["abc","def","ghi","xyz"]})

In [176]:
df3

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [177]:
df3["col2"].unique()

array([444, 555, 666], dtype=int64)

In [178]:
df3["col2"].nunique()

3

In [180]:
len(df3["col2"])

4

In [181]:
df3["col2"].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [184]:
df3

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [196]:
new_df = df3[(df3["col2"] == 444) | (df3["col1"]>2)]

In [197]:
new_df

col1  col2 col3
0     1   444  abc
2     3   666  ghi
3     4   444  xyz

In [198]:
df3[(df3["col2"] == 444) & (df3["col1"]>2)]

col1  col2 col3
3     4   444  xyz

In [200]:
def times_two(number):
    return(number*2)

In [203]:
df3["col1"].apply(times_two)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [205]:
df3["col1*2"] = df3["col1"].apply(times_two,) 

In [211]:
df3

col1  col2 col3  col1*2
0     1   444  abc       2
1     2   555  def       4
2     3   666  ghi       6
3     4   444  xyz       8

In [212]:
del df3["col1*2"]

In [213]:
df3

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [214]:
df3.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [215]:
df3.index

RangeIndex(start=0, stop=4, step=1)

In [216]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
col1    4 non-null int64
col2    4 non-null int64
col3    4 non-null object
dtypes: int64(2), object(1)
memory usage: 176.0+ bytes


In [220]:
df3.describe()

col1        col2
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

In [219]:
df3.describe().transpose()

count    mean         std    min     25%    50%     75%    max
col1    4.0    2.50    1.290994    1.0    1.75    2.5    3.25    4.0
col2    4.0  527.25  106.274409  444.0  444.00  499.5  582.75  666.0

# #################sort a data frame

In [221]:
df3.sort_values(by="col2", ascending = False)

col1  col2 col3
2     3   666  ghi
1     2   555  def
0     1   444  abc
3     4   444  xyz

In [225]:
df3["col2"].sort_values(ascending = False)

2    666
1    555
3    444
0    444
Name: col2, dtype: int64

# input and output

In [226]:
pwd

'C:\\Users\\pc\\Downloads'

In [232]:
df4 = pd.read_csv("example.csv")

In [233]:
df4

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [254]:
df5 = df4[["a","b","c"]]

In [255]:
df5

a   b   c
0   0   1   2
1   4   5   6
2   8   9  10
3  12  13  14

In [256]:
df5.to_csv("my_1st_data")

In [264]:
df6 = pd.read_excel("Excel_Sample.xlsx", sheet_name= "Sheet1")

In [268]:
df6

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15